AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  s3-thumbnail-generator
  Sample SAM Template for s3-thumbnail-generator

Globals:
  Api:
    BinaryMediaTypes:
      - "*/*"
  Function:
    Timeout: 3000
    Environment:
      Variables:
        THUMBNAIL_SIZE: 10
        REGION_NAME: "ap-south-1"
        BUCKET_NAME: !Sub "${AWS::StackName}-${AWS::Region}-${AWS::AccountId}"

Resources:
  S3ThumbnailGeneratorBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${AWS::StackName}-${AWS::Region}-${AWS::AccountId}" # #TOASK: Is setting bucket name like this the right way to do?

  UploadImageAndProcessThumbnailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: handlers/
      Handler: app.uploadImageAndProcessThumbnail
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3ThumbnailGeneratorBucket
      Events:
        UploadImageEvent:
          Type: Api
          Properties:
            Path: /uploadImage
            Method: POST

Outputs:
  UploadImageAndProcessThumbnailFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for UploadImageAndProcessThumbnailFunction function"
    Value: !Sub "https://${AWS::StackName}.execute-api.${AWS::Region}.${AWS::AccountId}.amazonaws.com/Prod/uploadImageAndProcessThumbnail/"
  UploadImageAndProcessThumbnailFunction:
    Description: "UploadImageAndProcessThumbnailFunction Lambda Function ARN"
    Value: !GetAtt UploadImageAndProcessThumbnailFunction.Arn
  UploadImageAndProcessThumbnailFunctionIamRole:
    Description: "Implicit IAM Role created for UploadImageAndProcessThumbnailFunction function"
    Value: !GetAtt UploadImageAndProcessThumbnailFunctionRole.Arn
